# Generated by Django 2.0.7 on 2018-08-02 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=200)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='history.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='Album_Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='history.Album')),
            ],
        ),
        migrations.RenameField(
            model_name='song',
            old_name='Artist',
            new_name='artist',
        ),
        migrations.AddField(
            model_name='album_song',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='history.Song'),
        ),
        migrations.AddField(
            model_name='album',
            name='songs',
            field=models.ManyToManyField(through='history.Album_Song', to='history.Song'),
        ),
    ]
